### ISSUE TITLE
Kevin Gong's methodology?

### ISSUE THREAD

**Issue by dandongus** [mikepound/opencubes#14]
Has anyone found any details as to how Kevin Gong approached this problem? [Apparently](http://kevingong.com/Polyominoes/Enumeration.html) he was able to enumerate n=16 in under 11 days time back in 2004 on a much slower/smaller computer than we have today, one would have to imagine he made some sort of breakthrough that no one here has happened across yet.

**Comment by VladimirFokow** [comment]
Here is a paper describing some theory: https://github.com/mikepound/opencubes/issues/5#issue-1802085753
