### ISSUE TITLE
On the use of sparse Matrices

### ISSUE THREAD

**Issue by Recouer** [mikepound/opencubes#16]
i believe using sparse matrices rather than using 3D matrices should reduce the amount of stored data by a fair amount.

**Comment by VladimirFokow** [comment]
I don't think the matrices that we have are sparce enough.
But really, I don't know. Of course, testing is needed to compare both approaches.

https://stackoverflow.com/a/36971131
> such a matrix has to store 3 arrays of values (at least in the coo format). So the sparsity has to be less than 1/3 to start saving memory

**Comment by VladimirFokow** [comment]
Great analysis!!

**Comment by bertie2** [comment]
good to know!
the C++ implementation already uses a sparse matrix, though that was because it made the rotation easier to understand by using conventional rotation matrices, but its great to know that that is likely optimal memory wise for large N as well.

**Comment by VladimirFokow** [comment]
@bertie2 I think what @Recouer is saying is that the sparse matrix is *not* optimal memory-wise

**Comment by bertie2** [comment]
@VladimirFokow no you are right I just completely misread, in which case changing the C++ version to work with bit arrays is back on the todo list.
