### ISSUE TITLE
pcube file format discussion

### ISSUE THREAD

**Issue by datdenkikniet** [mikepound/opencubes#23]
For (eventual) implementations that may support reading & writing cubes directly from disk to avoid having to store them in RAM, it would be really beneficial if we can write the count of cubes at the end of the file as well.

If writing the count to the end of the file is supported, cubes can be written to it in a streaming fashion and the count can be added at the end. If it's not supported, you have to rewrite the entire file from the beginning in order to fit the LEB128 encoding into the header.

Is there an easy way to support this?

I think we should definitely add a byte to the header that is just flags, with 1 bit explicitly reserved for increasing said header size (if we ever find more than 7 flags we need).

**Comment by bertie2** [comment]
so there is the proviso in the format that a cube_count of zero means ongoing stream.
I don't see how having the cube count at the end would help as reading to the end to read the cube count would be slower than just reading each cube as it comes?
or is their a fast way to skip straight to the end of the file ?

**Comment by datdenkikniet** [comment]
Yes, the streaming format I'm aware of.

There is no fast way to skip to the end of the file, but we could, encode the length of a trailer in the header.

You make a fair point about the finding the end. That could relatively easily be solved by encoding some trailer-length in the header.

The main purpose would be where the program is writing a very large file in a streaming fashion while keeping track of the count. Since the count is already there, it would save a bunch of effort if we could just tack it on to the end instead of requiring either an entire rewrite of the file, or requiring that whoever opens the file _must_ be OK with not knowing the amount of cubes in the file from the get-go

**Comment by datdenkikniet** [comment]
Okay, I have realized that my specific use case of "putting the cube count at the end" may not be super useful. I have, however, come up with a different thing that definitly requires the same infrastructure: writing blocks of cubes of the same size. This would entail:
1. A bit flag in the header indicating this format
2. For every block: an xyz in size, and a LEB128 number indicating the amount of cubes of that size following.

This would mean reducing the amount of data per cube 3 bytes, and perhaps increase the file density significantly.

This would also allow for far more efficient in-file deduplication

**Comment by datdenkikniet** [comment]
Closing in favor of #8
