### ISSUE TITLE
Licence for opencubes

### ISSUE THREAD

**Issue by NailLegProcessorDivide** [mikepound/opencubes#33]
This was brought up for the original cubes repository and an MIT Licence was added however this repository still has no licence.
To my understanding (IANAL) we would need to get agreement from every contributor for licensing this which may have been the issue as to why it wasnt fixed at the same time but would also imply that this is something that is easier to fix sooner rather than later.

**Comment by bertie2** [comment]
@nsch0e @NailLegProcessorDivide @datdenkikniet @JATothrim @joulebit @VladimirFokow 
and myself are the current contributors, could I get a confirmation from all of you to MIT license this.

**Comment by datdenkikniet** [comment]
Confirm, I think this is a great idea. Let's add it ASAP

**Comment by VladimirFokow** [comment]
I also agree to the MIT license

**Comment by NailLegProcessorDivide** [comment]
I also agree

**Comment by nsch0e** [comment]
I also agree

**Comment by JATothrim** [comment]
I agree with MIT license.

**Comment by datdenkikniet** [comment]
Generally MIT licensed projects only include the license in a LICENSE file.

If we want to be on the safe side we could include an [SPDX header], but I don't think it's necessary

[SPDX header]: https://spdx.github.io/spdx-spec/v2.3/using-SPDX-short-identifiers-in-source-files/

**Comment by bertie2** [comment]
unfortunately I am unable to get in contact with @joulebit , I will be backing out his changes in order to apply the MIT license to all other code which contributors here have agreed to.

**Comment by mikepound** [comment]
I'm happy with MIT, and happy for you to make the call. Originally I'd thought of a fairly generic wording for "developers" like the one used in the numpy mit license:

https://numpy.org/devdocs/license.html
